# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SIP
version:      0.40
version_from: lib/Net/SIP.pm
installdirs:  site
requires:
    Net::DNS:                      0.56

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
